### ISSUE TITLE
本地调用bug

### ISSUE THREAD

**Issue by javamonkey** [javamonkey/beetl2.0#300]
var d = 0.5;
var str = @java.lang.String.valueOf(0.5)

报错

java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Character
	at org.beetl.core.om.ObjectMethodMatchConf.convert(ObjectMethodMatchConf.java:125)
	at org.beetl.core.om.ObjectMethodMatchConf.convert(ObjectMethodMatchConf.java:80)
	at org.beetl.core.om.ObjectUtil.invoke(ObjectUtil.java:541)

**Comment by javamonkey** [comment]
比较难搞，会出现不兼容
