### ISSUE TITLE
注释错误，提示不明显

### ISSUE THREAD

**Issue by javamonkey** [javamonkey/beetl2.0#337]
java.lang.ClassCastException: org.antlr.v4.runtime.tree.ErrorNodeImpl cannot be cast to org.antlr.v4.runtime.ParserRuleContext
	at org.beetl.core.AntlrProgramBuilder.build(AntlrProgramBuilder.java:235)
	at org.beetl.core.engine.DefaultTemplateEngine.createProgram(DefaultTemplateEngine.java:60)

当注释错误的时候
<%
/* dsfsdfsdf */
var a=1;

*/

%>
${a}

**Comment by javamonkey** [comment]
`>>06:47:35:缺少符号(PARSER_MISS_ERROR):; 位于3行 资源:/hello.txt
缺少输入在 ';' 后面， 期望 <EOF>
1|<%
2|/* dsfsdfsdf */
3|var a=1;
4|
5|*/
6|
7|%>`

**Comment by javamonkey** [comment]
`
<%
/* dsfsdfsdf 
var a=1;



%>
${a}
`

这种注释情况，缺少注释，应该警告，
