### ISSUE TITLE
自定义标签的属性中使用dateFormat格式化出现语法错误

### ISSUE THREAD

**Issue by think-gem** [javamonkey/beetl2.0#366]
自定义标签的属性中使用dateFormat格式化出现语法错误，错误如下：（使用版本 beetl-2.7.26）
```
>>03:06:54:语法错误(PARSER_VIABLE_ERROR):, 位于85行 资源:/modules/test/testDataForm.html
'htmltag('form:input',{"name":"testDate","readonly":"true","class":"form-control",\n"value":(testData.testDate,'
82|                                <span class="required hide">*</span> 日期选择：<i class="fa icon-question hide"></i></label> 
83|                            <div class="col-sm-8"> 
84|                                <#form:input name="testDate" readonly="true" class="form-control" 
85|                                    value="${testData.testDate,dateFormat='yyyy-MM-dd HH:mm'}"/> 
86|                            </div> 
87|                        </div> 
88|                    </div> 

    at org.beetl.core.Template.renderTo(Template.java:169) 
    at org.beetl.core.Template.renderTo(Template.java:89) 
    at org.beetl.ext.web.WebRender.render(WebRender.java:125) 
    at org.beetl.ext.spring.BeetlSpringView.renderMergedTemplateModel(BeetlSpringView.java:123) 

此处省略...

    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) 
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
    at java.lang.Thread.run(Thread.java:748) 
Caused by: PARSER_VIABLE_ERROR 
    at org.beetl.core.parser.BeetlAntlrErrorStrategy.reportNoViableAlternative(BeetlAntlrErrorStrategy.java:145) 
    at org.beetl.core.parser.BeetlAntlrErrorStrategy.reportError(BeetlAntlrErrorStrategy.java:103) 
    at org.beetl.core.parser.BeetlParser.statement(BeetlParser.java:622) 
	
此处省略...

    at org.beetl.core.GroupTemplate.loadTemplate(GroupTemplate.java:657) 
    at org.beetl.core.GroupTemplate.getTemplateByLoader(GroupTemplate.java:595) 
    at org.beetl.core.GroupTemplate.getTemplate(GroupTemplate.java:547) 
    at org.beetl.ext.web.WebRender.render(WebRender.java:85) 
    ... 56 more 
Caused by: org.antlr.v4.runtime.NoViableAltException 
    at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2025) 
    at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467) 
    at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393) 
    at org.beetl.core.parser.BeetlParser.statement(BeetlParser.java:376) 
    ... 69 more
```

**Comment by javamonkey** [comment]
文档已经说说明了，html标签不支持格式化函数，因为html标签属性主要是给标签传递变量，而不是格式化输出。目前也没考虑支持这个特性，你可以在标签实现里格式化输出
